name: Jekyll site CI

on:
  push:
    branches: [ crystal ]
  pull_request:
    branches: [ crystal ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Deploy OSS
      uses: nevermin/deploy-aliyun-oss@main
      with:
        # aliyun config
        region: oss-cn-hongkong
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
        bucket: ${{ secrets.BUCKET }}
        secure: true
        maxSockets: 3
        # deploy config
        entry: _site/**/* # glob pattern
        remote-dir: /
        path-rewrite: ^_site/
