name: Jekyll site CI

on:
  push:
    branches: [ crystal ]
  pull_request:
    branches: [ crystal ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
    - run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: upload files to OSS
      uses: nevermin/aliyun-oss-website-action@v1
      with:
        accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
        accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
        bucket: ${{ secrets.BUCKET }}
        # use your own endpoint
        endpoint: oss-cn-hongkong.aliyuncs.com
        folder: ./_site/

